from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from typing import List
from models import TimeSlot, TimetableConstraints, Day
import tempfile


def generate_pdf(schedule: List[TimeSlot], constraints: TimetableConstraints) -> str:
    """
    Generate a PDF of the timetable.
    Returns the path to the generated PDF file.
    """
    # Create temporary file
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.pdf')
    pdf_path = temp_file.name
    temp_file.close()

    # Create PDF document
    doc = SimpleDocTemplate(pdf_path, pagesize=A4)
    elements = []

    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2C3E50'),
        spaceAfter=30,
        alignment=1  # Center
    )

    # Add title
    title = Paragraph("My Randomized Timetable", title_style)
    elements.append(title)
    elements.append(Spacer(1, 0.3 * inch))

    # Organize schedule into grid
    days = constraints.days_per_week
    periods_per_day = constraints.periods_per_day

    # Create schedule dictionary for easy lookup
    schedule_dict = {}
    for slot in schedule:
        key = (slot.day, slot.period)
        schedule_dict[key] = slot

    # Build table data
    table_data = []

    # Header row
    header_row = ['Period'] + [day.value for day in days]
    table_data.append(header_row)

    # Data rows
    for period in range(1, periods_per_day + 1):
        row = [f'Period {period}']

        for day in days:
            key = (day, period)
            if key in schedule_dict:
                slot = schedule_dict[key]
                cell_text = f"{slot.class_name}\n{slot.teacher}"
                row.append(cell_text)
            elif constraints.lunch_break_period and period == constraints.lunch_break_period:
                row.append("LUNCH BREAK")
            else:
                row.append("-")

        table_data.append(row)

    # Create table
    table = Table(table_data, colWidths=[1.2 * inch] + [1.3 * inch] * len(days))

    # Style the table
    table_style = TableStyle([
        # Header styling
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#34495E')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),

        # First column (periods)
        ('BACKGROUND', (0, 1), (0, -1), colors.HexColor('#ECF0F1')),
        ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),

        # Body styling
        ('FONTNAME', (1, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (1, 1), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#BDC3C7')),
        ('ROWBACKGROUNDS', (1, 1), (-1, -1), [colors.white, colors.HexColor('#F8F9FA')]),
    ])

    table.setStyle(table_style)
    elements.append(table)

    # Add footer
    elements.append(Spacer(1, 0.5 * inch))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#7F8C8D'),
        alignment=1
    )
    footer = Paragraph("Generated by Timetable Randomizer ✨", footer_style)
    elements.append(footer)

    # Build PDF
    doc.build(elements)

    return pdf_path
